on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      secrets:
        envPAT:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-lastest
    environment: production
    steps:
    - uses: actions/labeler@v4
      with:
      repo-token: ${{ secrets.envPAT }}
      configuration-path: ${{ inputs.config-path }}
  
  jobs:
  call-workflow-passing-data:
    uses: whsalazar-org/demo/.github/workflows/calledreusabledemo.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit
