name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://github.com
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        id: job_context_step
        run: echo '${{ toJSON(job) }}'
      - name: dump step context
        id: step_context_step
        run: echo '${{ toJSON(steps) }}'
        
        






