name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://github.com
    steps:
    - name: dump step context
      run: echo '${{ toJSON(steps) }}'





