on:
	workflow_call:
	inputs:
		config-path:
			required: true
			type: string
	 secrets:
	 		envPAT:
				required: true
jobs:
	resuable_workflow_job:
	runs-on: ubuntu-lastest
	environment: production
	steps:
	- uses: actions/labeler@v4
		with:
			repo-token: ${{ secrets.envPAT }}
			configurtion-path: ${{ inputs.config-path }}
